language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install --upgrade pip setuptools
  - pip install numpy==1.12.0
  - python setup.py install
  - pip install -r dev-requirements.txt

script: nosetests

after_success: coveralls
